In [1]:
import numpy as np
import pandas as pd

1.1 Дан   произвольный   список, содержащий только числа.Выведите результат сложения всех чисел больше 10. 

In [2]:
a=np.random.randint(1,30,20)
a

array([ 4, 14, 28, 16, 24,  1, 15,  3,  3, 28,  6,  8, 14, 10,  2, 13, 10,
       20, 24, 25])

In [3]:
sum([x for x in a if x>10])

221

1.2 Пусть   задан   список, содержащий строки.Выведите все строки, заканчивающиеся буквой r.

In [4]:
b=['flower','book','instagram','bird','clover']
for i in b:
    if i[-1]=='r': print(i)

flower
clover


1.3 Сгенерируйте и выведите cлучайную строку размером 6 символов, содержащуютолько цифры. Строка должна содержать хотя бы однуцифру 3.

In [5]:
c=np.random.randint(1,10,6)
c[np.random.randint(len(c))]=3
c

array([3, 4, 9, 5, 4, 9])

In [6]:
''.join(str(y) for y in c)

'349549'

1.4 Пусть   дана строка произвольной длины. Выведите информацию о том,сколько в ней символов и сколько слов.

In [7]:
d='Пусть дана строка произвольной длины. Выведите информацию о том, сколько в ней символов и сколько слов.'
len(d.split(' '))

16

In [8]:
len(''.join(z for z in d.split(' ')))

88

2.1 Пусть   дана матрица чисел размером NхN. Представьте данную матрицу ввиде списка. Выведите результат сложения всех элементов матрицы.

In [9]:
N=15
f=(np.random.randint(1,50,N*N)).reshape(N,N)
f

array([[11, 13, 22, 11,  3, 29,  3, 29, 19, 21, 13, 44,  9, 38, 28],
       [ 4, 15, 33, 15, 34, 13, 49, 38, 47, 33, 27, 28, 23, 38, 28],
       [14, 11, 20,  8, 14,  3, 40, 19, 31, 18, 44, 24, 44, 25,  9],
       [38, 34,  1,  3, 45, 37, 38, 36,  9, 24, 32,  4, 46, 33,  1],
       [15, 20, 14, 11,  3, 22, 43, 26, 27,  6, 42, 23, 39, 45, 11],
       [ 1, 25, 26, 27,  9, 34,  2, 40,  8,  2, 46, 47,  6, 32, 11],
       [45,  2, 35, 49, 36, 20,  5, 19, 17, 30, 20, 40, 36, 34, 38],
       [30,  2, 18, 29,  1, 42, 14, 33,  2, 49, 37, 34, 28,  8, 18],
       [31,  2, 25, 26, 20, 27,  5, 19,  5, 19, 20, 39,  8,  1, 37],
       [33, 46, 35, 18, 21, 17, 27,  8, 33, 33, 25, 15,  9, 46, 10],
       [39,  5, 20, 43, 32, 12, 10, 13, 41, 49, 15, 34,  4, 18, 31],
       [34, 13, 29, 44,  4, 48, 39, 28, 23,  1, 37, 28,  4,  4, 32],
       [28, 13, 19, 35, 20,  5, 44, 36, 31,  9, 37,  7, 37, 41,  3],
       [37, 30, 19, 27, 19, 41,  9, 15, 30, 14, 49, 33, 15, 46, 38],
       [49, 31, 35, 12, 49,  4,  3

In [10]:
f=f.reshape(N*N)
f

array([11, 13, 22, 11,  3, 29,  3, 29, 19, 21, 13, 44,  9, 38, 28,  4, 15,
       33, 15, 34, 13, 49, 38, 47, 33, 27, 28, 23, 38, 28, 14, 11, 20,  8,
       14,  3, 40, 19, 31, 18, 44, 24, 44, 25,  9, 38, 34,  1,  3, 45, 37,
       38, 36,  9, 24, 32,  4, 46, 33,  1, 15, 20, 14, 11,  3, 22, 43, 26,
       27,  6, 42, 23, 39, 45, 11,  1, 25, 26, 27,  9, 34,  2, 40,  8,  2,
       46, 47,  6, 32, 11, 45,  2, 35, 49, 36, 20,  5, 19, 17, 30, 20, 40,
       36, 34, 38, 30,  2, 18, 29,  1, 42, 14, 33,  2, 49, 37, 34, 28,  8,
       18, 31,  2, 25, 26, 20, 27,  5, 19,  5, 19, 20, 39,  8,  1, 37, 33,
       46, 35, 18, 21, 17, 27,  8, 33, 33, 25, 15,  9, 46, 10, 39,  5, 20,
       43, 32, 12, 10, 13, 41, 49, 15, 34,  4, 18, 31, 34, 13, 29, 44,  4,
       48, 39, 28, 23,  1, 37, 28,  4,  4, 32, 28, 13, 19, 35, 20,  5, 44,
       36, 31,  9, 37,  7, 37, 41,  3, 37, 30, 19, 27, 19, 41,  9, 15, 30,
       14, 49, 33, 15, 46, 38, 49, 31, 35, 12, 49,  4,  3, 44, 33, 39, 29,
       38, 37, 40, 38])

In [11]:
f.sum()

5519

2.2 Дана матрица размером NxM. Напишите алгоритм вычисления максимума из сумм элементов каждого столбца.

In [12]:
N=15
M=23
g=(np.random.randint(1,50,N*M)).reshape(N,M)
g

array([[48, 47, 17, 40, 14, 38, 49, 18, 10, 33, 12,  5, 28, 32,  4, 31,
        28, 19, 32, 32, 22, 14, 18],
       [14, 16, 32, 37, 12,  9, 37, 16, 19,  4, 27,  8, 28,  9, 46,  7,
        15, 30, 19, 43,  8, 19, 18],
       [17, 32,  5, 30, 21,  3, 28, 49, 23, 41,  5, 44, 32, 47, 38, 39,
        34, 28, 14, 15,  6, 22, 18],
       [35, 36, 23, 17, 31, 22, 20, 20, 38, 30, 28, 37, 32, 19, 46, 19,
        21, 17,  9, 36, 18, 47, 15],
       [ 3, 31, 29, 13, 36,  4,  8, 25, 35,  6, 25, 14, 45, 15, 35, 28,
        49,  8,  6, 42, 26, 34, 40],
       [44, 26, 43, 42,  5, 39, 18, 35, 34, 41, 44, 35, 40, 31,  3,  3,
        38, 43, 35, 34, 28, 34,  3],
       [ 7,  8, 16, 25, 18, 31, 10, 21, 43,  5, 46, 46, 30, 43, 14, 45,
        29, 47, 17, 21,  4, 13, 29],
       [25, 44, 46, 11, 33, 45, 15, 31, 36,  5, 49,  3,  1, 24, 30, 14,
        33, 42, 25, 47, 15, 26, 37],
       [11, 37, 47, 21, 46, 35, 29, 25,  7, 34,  3,  3, 31, 35, 12, 10,
        45, 29, 48, 15, 17, 14, 26],
       [ 6, 29, 32,

In [13]:
max([i.sum() for i in g])

698

3.1 Пусть   список студентов представлен в виде структуры [[No, ФИО, Возраст,Группа],[No, ФИО, Возраст, Группа],[No, ФИО, Возраст, Группа]]. Преобразуйте список в словарь вида: {No: [ФИО, Возраст, Группа], No:[....], No: [....]}

In [16]:
students=[[201901, 'Ivanov Ivan Ivanovich', 23, 947],
         [201902, 'Petrov Petr Petrovich', 22, 941],
         [201903, 'Sidorov Cider Sidorovich', 21, 949],
         [201904, 'Lebedev Michail Alexandrovich', 22, 943]]
studs={i[0]:i[1:] for i in students}
studs

{201901: ['Ivanov Ivan Ivanovich', 23, 947],
 201902: ['Petrov Petr Petrovich', 22, 941],
 201903: ['Sidorov Cider Sidorovich', 21, 949],
 201904: ['Lebedev Michail Alexandrovich', 22, 943]}

3.2 Напишите алгоритм, позволяющий найти запись в словаре из задачи 3.1 (без преобразования словаря обратно в список) по фамилии и изменить в ней номер группы. Фамилию и новый номер группы необходимо ввести с клавиатуры.

In [20]:
h=input("Enter surname:")
j=input("New group number:")
for key,value in studs.items():
    if h in value[0]: value[2]=int(j)
studs

Enter surname:Ivanov
New group number:951


{201901: ['Ivanov Ivan Ivanovich', 23, 951],
 201902: ['Petrov Petr Petrovich', 19, 941],
 201903: ['Sidorov Cider Sidorovich', 21, 949],
 201904: ['Lebedev Michail Alexandrovich', 22, 943]}

3.3 Напишите алгоритм, позволяющий аналогично задаче 3.2 изменить возраст студент

In [21]:
k=input("Enter surname:")
l=input("New age value:")
for key,value in studs.items():
    if k in value[0]: value[1]=int(l)
studs

Enter surname:Petrov
New age value:19


{201901: ['Ivanov Ivan Ivanovich', 23, 951],
 201902: ['Petrov Petr Petrovich', 19, 941],
 201903: ['Sidorov Cider Sidorovich', 21, 949],
 201904: ['Lebedev Michail Alexandrovich', 22, 943]}